pipeline:
  name: test-gradle-parallel
  identifier: testgradleparallel
  projectIdentifier: tiagentdev
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: avijeetgradletest
        build: <+input>
  stages:
    - stage:
        name: test
        identifier: test
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: false
            paths: []
          buildIntelligence:
            enabled: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - parallel:
                  - step:
                      type: Test
                      name: Test_1
                      identifier: Test_1
                      spec:
                        shell: Sh
                        command: ./gradlew test
                        intelligenceMode: true
                      strategy:
                        parallelism: 2
                  - step:
                      type: RunTests
                      name: RunTests_1
                      identifier: RunTests_1
                      spec:
                        language: Java
                        buildTool: Gradle
                        args: test
                        runOnlySelectedTests: true
                        reports:
                          type: JUnit
                          spec:
                            paths:
                              - "**/*.xml"
                        enableTestSplitting: true
                        testSplitStrategy: TestCount
                      strategy:
                        parallelism: 2
