pipeline:
  name: ti-gfibre
  identifier: tigfibre
  projectIdentifier: tiagentdev
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: tigfibretest
        build: <+input>
        sparseCheckout: []
  stages:
    - stage:
        name: ti
        identifier: ti
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: false
            paths: []
          buildIntelligence:
            enabled: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Test
                  name: Test_1
                  identifier: Test_1
                  spec:
                    shell: Sh
                    command: |
                      echo $TI_OUTPUT_PATH
                      echo "Current user: $USER"
                      ./gradlew test
                      test_status=$?
                      ls -lart $TI_OUTPUT_PATH
                      ls -lart $TI_OUTPUT_PATH
                      echo "result test: $test_status"
                      if [ $test_status -ne 0 ]; then
                          echo "IN IF"
                          rm -rf $TI_OUTPUT_PATH
                      fi
                      ls -lart $TI_OUTPUT_PATH
                      rm -rf $TI_OUTPUT_PATH
                      ls -lart $(dirname "$TI_OUTPUT_PATH")
                    intelligenceMode: true
