pipeline:
  name: ti-gfibre
  identifier: tigfibre
  projectIdentifier: tiagentdev
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: tigfibretest
        build: <+input>
        sparseCheckout: []
  stages:
    - stage:
        name: ti
        identifier: ti
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: false
            paths: []
          buildIntelligence:
            enabled: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Test
                  name: Test_1
                  identifier: Test_1
                  spec:
                    shell: Bash
                    command: |-
                      if ./gradlew test; then
                          test_success=1
                      else
                          test_success=0
                      fi

                      if [[ $test_success -eq 1 ]]; then
                          rm -rf "$TI_OUTPUT_PATH"
                      fi
                    intelligenceMode: true
